/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package vista;

import controlador.controladorPantallaProductos;
import java.sql.Date;
import java.util.regex.Pattern;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import modelo.vo.Cliente;
import modelo.vo.Empleado;
import modelo.vo.ProductoFinanciero;
import modelo.vo.VenderPK;

/**
 *
 * @author dami2
 */
public class PantallaProductos extends javax.swing.JFrame {

    private boolean comboCarg;
    /**
     * Creates new form PantallaProductos
     */
    public PantallaProductos() {
 comboCarg=false;
        initComponents();
        controladorPantallaProductos.iniciarSession();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        btnVendIns = new javax.swing.JButton();
        btnCliMod = new javax.swing.JButton();
        txtCliVer = new javax.swing.JButton();
        cmbVendProd = new javax.swing.JComboBox<>();
        cmbVendCli = new javax.swing.JComboBox<>();
        cmbVendEmp = new javax.swing.JComboBox<>();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lblFecha = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtProdCod = new javax.swing.JTextField();
        txtProdInt = new javax.swing.JTextField();
        txtProdfecha = new javax.swing.JTextField();
        txtProdPunt = new javax.swing.JTextField();
        cmbProdTipo = new javax.swing.JComboBox<>();
        btnProdIns = new javax.swing.JButton();
        btnProdBorrar = new javax.swing.JButton();
        btnProdMod = new javax.swing.JButton();
        btnProdVer = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtProdArea = new javax.swing.JTextArea();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtVendArea = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Vender"));

        jLabel7.setText("Producto");

        jLabel8.setText("Cliente");

        jLabel9.setText("Empleado");

        btnVendIns.setText("Insertar");
        btnVendIns.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnVendInsMouseClicked(evt);
            }
        });

        btnCliMod.setText("Modificar");
        btnCliMod.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCliModMouseClicked(evt);
            }
        });

        txtCliVer.setText("Visualizar");
        txtCliVer.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtCliVerMouseClicked(evt);
            }
        });

        cmbVendProd.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmbVendProdItemStateChanged(evt);
            }
        });
        cmbVendProd.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                cmbVendProdPropertyChange(evt);
            }
        });

        cmbVendCli.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmbVendCliItemStateChanged(evt);
            }
        });
        cmbVendCli.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                cmbVendCliPropertyChange(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(txtCliVer))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                                .addComponent(cmbVendEmp, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel7))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cmbVendProd, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cmbVendCli, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 44, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnVendIns, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(2, 2, 2)
                                .addComponent(btnCliMod)))))
                .addGap(32, 32, 32))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(38, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(cmbVendProd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnVendIns))
                        .addGap(25, 25, 25)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cmbVendCli, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8))
                        .addGap(27, 27, 27))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(btnCliMod)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(cmbVendEmp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtCliVer)
                .addGap(68, 68, 68))
        );

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Producto financiero"));

        jLabel1.setText("Código");

        jLabel2.setText("Puntuación");

        lblFecha.setText("Fecha devolución");

        jLabel5.setText("Interés");

        jLabel6.setText("Tipo");

        txtProdCod.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtProdCodFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtProdCodFocusLost(evt);
            }
        });
        txtProdCod.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtProdCodActionPerformed(evt);
            }
        });

        cmbProdTipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Financiación", "Ahorro", "Inversión" }));
        cmbProdTipo.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                cmbProdTipoPropertyChange(evt);
            }
        });

        btnProdIns.setText("Insertar");
        btnProdIns.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnProdInsMouseClicked(evt);
            }
        });

        btnProdBorrar.setText("Borrar");
        btnProdBorrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnProdBorrarMouseClicked(evt);
            }
        });

        btnProdMod.setText("Modificar");
        btnProdMod.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnProdModMouseClicked(evt);
            }
        });

        btnProdVer.setText("Visualizar");
        btnProdVer.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnProdVerMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(50, 50, 50)
                        .addComponent(txtProdPunt, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addComponent(lblFecha)
                        .addGap(18, 18, 18)
                        .addComponent(txtProdfecha))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                            .addComponent(jLabel5)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtProdInt, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel1)
                                    .addGap(22, 22, 22))
                                .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.LEADING))
                            .addGap(50, 50, 50)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(txtProdCod)
                                .addComponent(cmbProdTipo, 0, 142, Short.MAX_VALUE)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 42, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnProdMod, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnProdVer, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnProdBorrar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnProdIns, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnProdIns)
                        .addComponent(cmbProdTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel6))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnProdBorrar)
                        .addGap(21, 21, 21))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(txtProdCod, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnProdMod)
                    .addComponent(jLabel5)
                    .addComponent(txtProdInt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnProdVer)
                    .addComponent(txtProdPunt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblFecha)
                    .addComponent(txtProdfecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        txtProdArea.setColumns(20);
        txtProdArea.setRows(5);
        jScrollPane2.setViewportView(txtProdArea);

        txtVendArea.setColumns(20);
        txtVendArea.setRows(5);
        jScrollPane1.setViewportView(txtVendArea);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane2)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 251, Short.MAX_VALUE)
                    .addComponent(jScrollPane1))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtProdCodActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtProdCodActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtProdCodActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        controladorPantallaProductos.cargarCb();
        comboCarg=true;
    }//GEN-LAST:event_formWindowOpened

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        // TODO add your handling code here:
        comboCarg=false;
    }//GEN-LAST:event_formWindowClosed

    private void cmbProdTipoPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_cmbProdTipoPropertyChange
        // TODO add your handling code here:
        if (evt.getPropertyName().equals("selectedItem")) {
            if (evt.getNewValue().equals("Financiación")) {
                lblFecha.setVisible(true);
                txtProdfecha.setVisible(true);
            } else {
                lblFecha.setVisible(false);
                txtProdfecha.setVisible(false);
            }
        }
    }//GEN-LAST:event_cmbProdTipoPropertyChange

    private void cmbVendProdPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_cmbVendProdPropertyChange
        // TODO add your handling code here:
        if (evt.getPropertyName().equals("selectedItem")) {
            ProductoFinanciero p = (ProductoFinanciero) cmbVendProd.getSelectedItem();
            Cliente c = (Cliente) cmbVendCli.getSelectedItem();
            VenderPK vpk = new VenderPK(p.getCodProducto(), c.getIdCliente());
            controladorPantallaProductos.cargarDatosVend(vpk, cmbProdTipo);
        }
    }//GEN-LAST:event_cmbVendProdPropertyChange

    private void cmbVendCliPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_cmbVendCliPropertyChange
        // TODO add your handling code here:
        if (evt.getPropertyName().equals("selectedItem")) {
            ProductoFinanciero p = (ProductoFinanciero) cmbVendProd.getSelectedItem();
            Cliente c = (Cliente) cmbVendCli.getSelectedItem();

            VenderPK vpk = new VenderPK(p.getCodProducto(), c.getIdCliente());
            controladorPantallaProductos.cargarDatosVend(vpk, cmbVendEmp);
        }
    }//GEN-LAST:event_cmbVendCliPropertyChange

    private void txtProdCodFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtProdCodFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_txtProdCodFocusGained

    private void txtProdCodFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtProdCodFocusLost
        // TODO add your handling code here:
        if (!txtProdCod.getText().isBlank()) {
        controladorPantallaProductos.cargarDatosPro(txtProdCod.getText(), txtProdfecha, txtProdInt, txtProdPunt, cmbProdTipo);
        }
    }//GEN-LAST:event_txtProdCodFocusLost

    private void btnProdInsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnProdInsMouseClicked
        // TODO add your handling code here:
        boolean correcto=validarProducto();
        if(correcto==true){
        controladorPantallaProductos.insertarPro(txtProdCod.getText(), Date.valueOf(txtProdfecha.getText()), Float.valueOf(txtProdInt.getText()), txtProdPunt.getText(), cmbProdTipo.getSelectedItem().toString());
        }
    }//GEN-LAST:event_btnProdInsMouseClicked

    private void btnProdBorrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnProdBorrarMouseClicked
        // TODO add your handling code here:
        boolean correcto=validarProducto();
        if(correcto==true){
        controladorPantallaProductos.borrarPro(txtProdCod.getText());
        }
    }//GEN-LAST:event_btnProdBorrarMouseClicked

    private void btnProdModMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnProdModMouseClicked
        // TODO add your handling code here:
        boolean correcto=validarProducto();
        if(correcto==true){
        controladorPantallaProductos.modificarPro(txtProdCod.getText(), Date.valueOf(txtProdfecha.getText()), Float.valueOf(txtProdInt.getText()), txtProdPunt.getText(), cmbProdTipo.getSelectedItem().toString());
        }
    }//GEN-LAST:event_btnProdModMouseClicked

    private void btnProdVerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnProdVerMouseClicked
        // TODO add your handling code here:
        controladorPantallaProductos.VisualizarPro(txtProdArea);
    }//GEN-LAST:event_btnProdVerMouseClicked

    private void btnVendInsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnVendInsMouseClicked
        // TODO add your handling code here:
        ProductoFinanciero p = (ProductoFinanciero) cmbVendProd.getSelectedItem();
        Cliente c = (Cliente) cmbVendCli.getSelectedItem();
        Empleado e = (Empleado) cmbVendEmp.getSelectedItem();
        VenderPK vpk = new VenderPK(p.getCodProducto(), c.getIdCliente());
        controladorPantallaProductos.insertarVend(vpk, e);
    }//GEN-LAST:event_btnVendInsMouseClicked

    private void btnCliModMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCliModMouseClicked
        // TODO add your handling code here:

        ProductoFinanciero p = (ProductoFinanciero) cmbVendProd.getSelectedItem();
        Cliente c = (Cliente) cmbVendCli.getSelectedItem();
        Empleado e = (Empleado) cmbVendEmp.getSelectedItem();
        VenderPK vpk = new VenderPK(p.getCodProducto(), c.getIdCliente());
        controladorPantallaProductos.modificarVend(vpk, e);
    }//GEN-LAST:event_btnCliModMouseClicked

    private void txtCliVerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtCliVerMouseClicked
        // TODO add your handling code here:
        controladorPantallaProductos.VisualizarVend(txtVendArea);
    }//GEN-LAST:event_txtCliVerMouseClicked

    private void cmbVendCliItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmbVendCliItemStateChanged
        // TODO add your handling code here:
        if(comboCarg==true){
       ProductoFinanciero p = (ProductoFinanciero) cmbVendProd.getSelectedItem();
            Cliente c = (Cliente) cmbVendCli.getSelectedItem();

            VenderPK vpk = new VenderPK(p.getCodProducto(), c.getIdCliente());
            controladorPantallaProductos.cargarDatosVend(vpk, cmbVendEmp);
        }
    }//GEN-LAST:event_cmbVendCliItemStateChanged

    private void cmbVendProdItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmbVendProdItemStateChanged
        // TODO add your handling code here:
        if(comboCarg==true){
         ProductoFinanciero p = (ProductoFinanciero) cmbVendProd.getSelectedItem();
            Cliente c = (Cliente) cmbVendCli.getSelectedItem();

            VenderPK vpk = new VenderPK(p.getCodProducto(), c.getIdCliente());
            controladorPantallaProductos.cargarDatosVend(vpk, cmbVendEmp);
        }
    }//GEN-LAST:event_cmbVendProdItemStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PantallaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PantallaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PantallaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PantallaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PantallaPrincipal().setVisible(true);
            }
        });

    }

    public JComboBox<Cliente> getCmbVendCli() {
        return cmbVendCli;
    }

    public JComboBox<Empleado> getCmbVendEmp() {
        return cmbVendEmp;
    }

    public JComboBox<ProductoFinanciero> getCmbVendProd() {
        return cmbVendProd;
    }

    private boolean validarProducto() {
        if (txtProdCod.getText().isBlank() == true) {
            JOptionPane.showMessageDialog(null, "Tiene que introducir el código");
            txtProdCod.requestFocus();
            return false;
        } else {
            Pattern p = Pattern.compile("^p\\d{2}$");
            boolean correcto = p.matcher(txtProdCod.getText()).matches();
            if (correcto == false) {
                JOptionPane.showMessageDialog(null, "Formato de código incorrecto(Formato válido:p+dos dígitos)");
                txtProdCod.requestFocus();
                txtProdCod.setText(" ");
                return false;
            }
        }
        if (txtProdInt.getText().isBlank() == true) {
            JOptionPane.showMessageDialog(null, "Tiene que introducir el interés");
            txtProdInt.requestFocus();
            return false;
        } else {
            for (int i = 0; i < txtProdInt.getText().length(); i++) {
                if (Character.isLetter(txtProdInt.getText().charAt(i))) {
                    JOptionPane.showMessageDialog(null, "El intéres solo pueden ser números");
                    txtProdInt.requestFocus();
                    txtProdInt.setText(" ");
                    return false;
                }
            }
        }
        if (txtProdPunt.getText().isBlank() == true) {
            JOptionPane.showMessageDialog(null, "Tiene que introducir la puntuación");
            txtProdPunt.requestFocus();
            return false;
        } else {
            Pattern p = Pattern.compile("^\\p{L}{3}");
            boolean correcto = p.matcher(txtProdPunt.getText()).matches();
            if (correcto == false) {
                JOptionPane.showMessageDialog(null, "Formato de puntuación incorrecto(Formato correcto:tres letras)");
                txtProdPunt.requestFocus();
                txtProdPunt.setText(" ");
                return false;
            }
        }
        if (cmbProdTipo.getSelectedItem().equals("Financiación")) {
            if (txtProdfecha.getText().isBlank() == true) {
                JOptionPane.showMessageDialog(null, "Tiene que introducir la fecha de devolución");
                txtProdfecha.requestFocus();
                return false;
            } else {
                try {
                    Date fecha = Date.valueOf(txtProdfecha.getText());

                } catch (IllegalArgumentException iae) {
                    JOptionPane.showMessageDialog(null, "Formato de fecha incorrecto(Formato correcto:yyyy-mm-dd)");
                    txtProdfecha.requestFocus();
                    txtProdfecha.setText(" ");
                    return false;
                }
            }
        }
        return true;
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCliMod;
    private javax.swing.JButton btnProdBorrar;
    private javax.swing.JButton btnProdIns;
    private javax.swing.JButton btnProdMod;
    private javax.swing.JButton btnProdVer;
    private javax.swing.JButton btnVendIns;
    private javax.swing.JComboBox<String> cmbProdTipo;
    private javax.swing.JComboBox<Cliente> cmbVendCli;
    private javax.swing.JComboBox<Empleado> cmbVendEmp;
    private javax.swing.JComboBox<ProductoFinanciero> cmbVendProd;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblFecha;
    private javax.swing.JButton txtCliVer;
    private javax.swing.JTextArea txtProdArea;
    private javax.swing.JTextField txtProdCod;
    private javax.swing.JTextField txtProdInt;
    private javax.swing.JTextField txtProdPunt;
    private javax.swing.JTextField txtProdfecha;
    private javax.swing.JTextArea txtVendArea;
    // End of variables declaration//GEN-END:variables
}
