/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

import controlador.controladorPantallaPrincipal;
import controlador.controladorPantallaProductos;
import controlador.controladorPantallaSucursal;
import java.time.LocalDate;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;

/**
 *
 * @author dami2
 */
public class PantallaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form PantallaPrincipal
     */
    public PantallaPrincipal() {
        initComponents();
        controladorPantallaPrincipal.iniciarSession();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtEmpCod = new javax.swing.JTextField();
        txtEmpNom = new javax.swing.JTextField();
        txtEmpContra = new javax.swing.JTextField();
        txtEmpUser = new javax.swing.JTextField();
        txtEmpDni = new javax.swing.JTextField();
        cmbEmpRol = new javax.swing.JComboBox<>();
        btnEmpIns = new javax.swing.JButton();
        btnEmpBorra = new javax.swing.JButton();
        btnEmpMod = new javax.swing.JButton();
        btnEmpVer = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        txtCliDni = new javax.swing.JTextField();
        txtCliNumC = new javax.swing.JTextField();
        txtCliCod = new javax.swing.JTextField();
        txtCliTlf = new javax.swing.JTextField();
        txtCliNom = new javax.swing.JTextField();
        btnCliIns = new javax.swing.JButton();
        btnCliBorrar = new javax.swing.JButton();
        btnCliMod = new javax.swing.JButton();
        txtCliVer = new javax.swing.JButton();
        btnTrbProd = new javax.swing.JButton();
        btnTrbSuc = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtEmpArea = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtCliArea = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Empleado"));

        jLabel1.setText("Código");

        jLabel2.setText("Usuario");

        jLabel3.setText("Contraseña");

        jLabel4.setText("Dni");

        jLabel5.setText("Nombre");

        jLabel6.setText("Rol");

        txtEmpCod.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtEmpCodFocusLost(evt);
            }
        });

        cmbEmpRol.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Director", "Inversionista", "Gestor de préstamos" }));

        btnEmpIns.setText("Insertar");
        btnEmpIns.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnEmpInsMouseClicked(evt);
            }
        });

        btnEmpBorra.setText("Borrar");
        btnEmpBorra.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnEmpBorraMouseClicked(evt);
            }
        });

        btnEmpMod.setText("Modificar");
        btnEmpMod.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnEmpModMouseClicked(evt);
            }
        });

        btnEmpVer.setText("Visualizar");
        btnEmpVer.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnEmpVerMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addGap(34, 34, 34)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(txtEmpUser, javax.swing.GroupLayout.DEFAULT_SIZE, 142, Short.MAX_VALUE)
                            .addComponent(txtEmpNom)
                            .addComponent(txtEmpCod)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtEmpContra)
                            .addComponent(txtEmpDni)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 61, Short.MAX_VALUE)
                        .addComponent(cmbEmpRol, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnEmpMod, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnEmpVer, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnEmpBorra, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnEmpIns, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtEmpCod, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEmpIns))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtEmpNom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEmpBorra))
                .addGap(21, 21, 21)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtEmpUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEmpMod))
                .addGap(19, 19, 19)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtEmpContra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEmpVer))
                .addGap(17, 17, 17)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtEmpDni, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(cmbEmpRol, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Cliente"));

        jLabel7.setText("Código");

        jLabel8.setText("Nombre");

        jLabel9.setText("Dni");

        jLabel10.setText("Teléfono");

        jLabel11.setText("Num.Cuenta");

        txtCliCod.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtCliCodFocusLost(evt);
            }
        });

        btnCliIns.setText("Insertar");
        btnCliIns.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCliInsMouseClicked(evt);
            }
        });

        btnCliBorrar.setText("Borrar");
        btnCliBorrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCliBorrarMouseClicked(evt);
            }
        });

        btnCliMod.setText("Modificar");
        btnCliMod.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCliModMouseClicked(evt);
            }
        });

        txtCliVer.setText("Visualizar");
        txtCliVer.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtCliVerMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel11)
                    .addComponent(jLabel10)
                    .addComponent(jLabel9)
                    .addComponent(jLabel8)
                    .addComponent(jLabel7))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtCliCod, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCliNom, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCliDni, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCliTlf, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCliNumC, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 44, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnCliMod, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtCliVer)
                    .addComponent(btnCliBorrar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnCliIns, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(34, 34, 34))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txtCliCod, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCliIns))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(txtCliNom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCliBorrar))
                .addGap(25, 25, 25)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(txtCliDni, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCliMod))
                .addGap(23, 23, 23)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(txtCliTlf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCliVer))
                .addGap(23, 23, 23)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(txtCliNumC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(66, 66, 66))
        );

        btnTrbProd.setText("Pantalla de productos/ventas");
        btnTrbProd.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnTrbProdMouseClicked(evt);
            }
        });

        btnTrbSuc.setText("Pantalla de sucursales/préstamos");
        btnTrbSuc.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnTrbSucMouseClicked(evt);
            }
        });

        txtEmpArea.setColumns(20);
        txtEmpArea.setRows(5);
        jScrollPane1.setViewportView(txtEmpArea);

        txtCliArea.setColumns(20);
        txtCliArea.setRows(5);
        jScrollPane2.setViewportView(txtCliArea);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnTrbSuc, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnTrbProd, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 264, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(22, 22, 22))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnTrbProd)
                        .addGap(27, 27, 27)
                        .addComponent(btnTrbSuc)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 230, Short.MAX_VALUE)
                    .addComponent(jScrollPane2)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnTrbProdMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnTrbProdMouseClicked
        // TODO add your handling code here:
        controladorPantallaProductos.iniciar();
    }//GEN-LAST:event_btnTrbProdMouseClicked

    private void btnTrbSucMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnTrbSucMouseClicked
        // TODO add your handling code here:
        controladorPantallaSucursal.iniciar();
    }//GEN-LAST:event_btnTrbSucMouseClicked

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        // TODO add your handling code here:
        controladorPantallaPrincipal.cerrarSession();
    }//GEN-LAST:event_formWindowClosed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowOpened

    private void txtEmpCodFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtEmpCodFocusLost
        // TODO add your handling code here:
        controladorPantallaPrincipal.cargarDatosEmp(txtEmpCod.getText(), txtEmpNom, txtEmpUser, txtEmpContra, txtEmpDni, cmbEmpRol);
    }//GEN-LAST:event_txtEmpCodFocusLost

    private void txtCliCodFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtCliCodFocusLost
        // TODO add your handling code here:
        controladorPantallaPrincipal.cargarDatosCli(txtCliCod.getText(), txtCliDni, txtCliNom, txtCliNumC, txtCliTlf);
    }//GEN-LAST:event_txtCliCodFocusLost

    private void btnEmpInsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEmpInsMouseClicked
        // TODO add your handling code here:
        validarEmpleado();
        controladorPantallaPrincipal.insertarEmp(txtEmpCod.getText(), txtEmpContra.getText(), txtEmpDni.getText(), txtEmpNom.getText(), cmbEmpRol.getSelectedItem().toString(), txtEmpUser.getText());
    
    }//GEN-LAST:event_btnEmpInsMouseClicked

    private void btnEmpBorraMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEmpBorraMouseClicked
        // TODO add your handling code here:
        validarEmpleado();
        controladorPantallaPrincipal.borrarEmp(txtEmpCod.getText());
    }//GEN-LAST:event_btnEmpBorraMouseClicked

    private void btnEmpModMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEmpModMouseClicked
        // TODO add your handling code here:
        validarEmpleado();
                controladorPantallaPrincipal.modificarEmp(txtEmpCod.getText(), txtEmpContra.getText(), txtEmpDni.getText(), txtEmpNom.getText(), cmbEmpRol.getSelectedItem().toString(), txtEmpUser.getText());

    }//GEN-LAST:event_btnEmpModMouseClicked

    private void btnEmpVerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEmpVerMouseClicked
        // TODO add your handling code here:
        controladorPantallaPrincipal.VisualizarEmp(txtEmpArea);
    }//GEN-LAST:event_btnEmpVerMouseClicked

    private void btnCliInsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCliInsMouseClicked
        // TODO add your handling code here:
        validarCliente();
         controladorPantallaPrincipal.insertarCli(txtCliCod.getText(), txtCliDni.getText(), txtCliNom.getText(), txtCliNumC.getText(), Integer.valueOf(txtCliTlf.getText()));
         
    }//GEN-LAST:event_btnCliInsMouseClicked

    private void btnCliBorrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCliBorrarMouseClicked
        // TODO add your handling code here:
        validarCliente();
        controladorPantallaPrincipal.borrarCli(txtCliCod.getText());
    }//GEN-LAST:event_btnCliBorrarMouseClicked

    private void btnCliModMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCliModMouseClicked
        // TODO add your handling code here:
          validarCliente();
         controladorPantallaPrincipal.modificarCli(txtCliCod.getText(), txtCliDni.getText(), txtCliNom.getText(), txtCliNumC.getText(), Integer.valueOf(txtCliTlf.getText()));
         
    }//GEN-LAST:event_btnCliModMouseClicked

    private void txtCliVerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtCliVerMouseClicked
        // TODO add your handling code here:
        controladorPantallaPrincipal.VisualizarCli(txtCliArea);
    }//GEN-LAST:event_txtCliVerMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PantallaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PantallaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PantallaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PantallaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PantallaPrincipal().setVisible(true);
            }
        });
    }

    private void validarEmpleado() {
        if (txtEmpCod.getText().isBlank() == true) {
            JOptionPane.showMessageDialog(null, "Tiene que introducir el código");
            txtEmpCod.requestFocus();
            return;
        } else {
            Pattern p = Pattern.compile("^e\\d{2}$");
            boolean correcto = p.matcher(txtEmpCod.getText()).matches();
            if (correcto == false) {
                JOptionPane.showMessageDialog(null, "Formato de código incorrecto(Formato válido:e+dos dígitos)");
                txtEmpCod.requestFocus();
                txtEmpCod.setText(" ");
                return;
            }
        }
        if (txtEmpNom.getText().isBlank() == true) {
            JOptionPane.showMessageDialog(null, "Tiene que introducir el nombre");
            txtEmpNom.requestFocus();
            return;
        } else {
            for (int i = 0; i < txtEmpNom.getText().length(); i++) {
                if (Character.isDigit(txtEmpNom.getText().charAt(i))) {
                    JOptionPane.showMessageDialog(null, "El nombre no puede tener números");
                    txtEmpNom.requestFocus();
                    txtEmpNom.setText(" ");
                    return;
                }
            }
        }
        if (txtEmpDni.getText().isBlank() == true) {
            JOptionPane.showMessageDialog(null, "Tiene que introducir el DNI");
            txtEmpDni.requestFocus();
            return;
        } else {
            Pattern p = Pattern.compile("^\\d{8}[A-HJ-NP-TV-Z]$");
            boolean correcto = p.matcher(txtEmpDni.getText()).matches();
            if (correcto == false) {
                JOptionPane.showMessageDialog(null, "Formato de DNI incorrecto");
                txtEmpDni.requestFocus();
                txtEmpDni.setText(" ");
                return;
            }
        }
       
    }
    
     private void validarCliente() {
        if (txtCliCod.getText().isBlank() == true) {
            JOptionPane.showMessageDialog(null, "Tiene que introducir el código");
            txtCliCod.requestFocus();
            return;
        } else {
            Pattern p = Pattern.compile("^c\\d{3}$");
            boolean correcto = p.matcher(txtCliCod.getText()).matches();
            if (correcto == false) {
                JOptionPane.showMessageDialog(null, "Formato de código incorrecto(Formato válido:c+tres dígitos)");
                txtCliCod.requestFocus();
                txtCliCod.setText(" ");
                return;
            }
        }
        if (txtCliNom.getText().isBlank() == true) {
            JOptionPane.showMessageDialog(null, "Tiene que introducir el nombre");
            txtCliNom.requestFocus();
            return;
        } else {
            for (int i = 0; i < txtCliNom.getText().length(); i++) {
                if (Character.isDigit(txtCliNom.getText().charAt(i))) {
                    JOptionPane.showMessageDialog(null, "El nombre no puede tener números");
                    txtCliNom.requestFocus();
                    txtCliNom.setText(" ");
                    return;
                }
            }
        }
        if (txtCliDni.getText().isBlank() == true) {
            JOptionPane.showMessageDialog(null, "Tiene que introducir el DNI");
            txtCliDni.requestFocus();
            return;
        } else {
            Pattern p = Pattern.compile("^\\d{8}[A-HJ-NP-TV-Z]$");
            boolean correcto = p.matcher(txtCliDni.getText()).matches();
            if (correcto == false) {
                JOptionPane.showMessageDialog(null, "Formato de DNI incorrecto");
                txtCliDni.requestFocus();
                txtCliDni.setText(" ");
                return;
            }
        }
         if (txtCliTlf.getText().isBlank() == true) {
            JOptionPane.showMessageDialog(null, "Tiene que introducir el teléfono");
            txtCliTlf.requestFocus();
            return;
        } else {
            Pattern p = Pattern.compile("^\\d{9}");
            boolean correcto = p.matcher(txtCliTlf.getText()).matches();
            if (correcto == false) {
                JOptionPane.showMessageDialog(null, "Formato de número de teléfono incorrecto");
                txtCliTlf.requestFocus();
                txtCliTlf.setText(" ");
                return;
            }
        }
         
         if (txtCliNumC.getText().isBlank() == true) {
            JOptionPane.showMessageDialog(null, "Tiene que introducir el número de cuenta");
            txtCliNumC.requestFocus();
            return;
        } else {
            Pattern p = Pattern.compile("^\\d{10}");
            boolean correcto = p.matcher(txtCliNumC.getText()).matches();
            if (correcto == false) {
                JOptionPane.showMessageDialog(null, "Formato de número de cuenta incorrecto");
                txtCliNumC.requestFocus();
                txtCliNumC.setText(" ");
                return;
            }
        }
       
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCliBorrar;
    private javax.swing.JButton btnCliIns;
    private javax.swing.JButton btnCliMod;
    private javax.swing.JButton btnEmpBorra;
    private javax.swing.JButton btnEmpIns;
    private javax.swing.JButton btnEmpMod;
    private javax.swing.JButton btnEmpVer;
    private javax.swing.JButton btnTrbProd;
    private javax.swing.JButton btnTrbSuc;
    private javax.swing.JComboBox<String> cmbEmpRol;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea txtCliArea;
    private javax.swing.JTextField txtCliCod;
    private javax.swing.JTextField txtCliDni;
    private javax.swing.JTextField txtCliNom;
    private javax.swing.JTextField txtCliNumC;
    private javax.swing.JTextField txtCliTlf;
    private javax.swing.JButton txtCliVer;
    private javax.swing.JTextArea txtEmpArea;
    private javax.swing.JTextField txtEmpCod;
    private javax.swing.JTextField txtEmpContra;
    private javax.swing.JTextField txtEmpDni;
    private javax.swing.JTextField txtEmpNom;
    private javax.swing.JTextField txtEmpUser;
    // End of variables declaration//GEN-END:variables
}
