/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package vista;

import controlador.controladorPantallaProductos;
import controlador.controladorPantallaSucursal;
import java.util.regex.Pattern;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import modelo.vo.PrestarPK;
import modelo.vo.Sucursal;
import modelo.vo.VenderPK;

/**
 *
 * @author dami2
 */
public class PantallaSucursal extends javax.swing.JFrame {
    boolean comboCarg;
    /**
     * Creates new form PantallaSucursal
     */
    public PantallaSucursal() {
        
        initComponents();
        controladorPantallaSucursal.iniciarSession();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txtPrestCant = new javax.swing.JTextField();
        btnPrestIns = new javax.swing.JButton();
        btnPrestMod = new javax.swing.JButton();
        txtPrestVer = new javax.swing.JButton();
        cmbPrestSucR = new javax.swing.JComboBox<>();
        cmbPrestSucPres = new javax.swing.JComboBox<>();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtSucCod = new javax.swing.JTextField();
        txtSucDir = new javax.swing.JTextField();
        txtSucTlf = new javax.swing.JTextField();
        btnSucIns = new javax.swing.JButton();
        btnSucBorrar = new javax.swing.JButton();
        btnSucMod = new javax.swing.JButton();
        btnSucVer = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtSucArea = new javax.swing.JTextArea();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtPrestArea = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Prestar"));

        jLabel7.setText("Sucursal");

        jLabel8.setText("Sucursal prestadora");

        jLabel10.setText("Cantidad");

        btnPrestIns.setText("Insertar");
        btnPrestIns.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnPrestInsMouseClicked(evt);
            }
        });

        btnPrestMod.setText("Modificar");
        btnPrestMod.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnPrestModMouseClicked(evt);
            }
        });

        txtPrestVer.setText("Visualizar");
        txtPrestVer.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtPrestVerMouseClicked(evt);
            }
        });

        cmbPrestSucR.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmbPrestSucRItemStateChanged(evt);
            }
        });
        cmbPrestSucR.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                cmbPrestSucRPropertyChange(evt);
            }
        });

        cmbPrestSucPres.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmbPrestSucPresItemStateChanged(evt);
            }
        });
        cmbPrestSucPres.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                cmbPrestSucPresPropertyChange(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(9, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cmbPrestSucR, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cmbPrestSucPres, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtPrestCant, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnPrestMod, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnPrestIns, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtPrestVer, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(34, 34, 34))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(42, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(cmbPrestSucR, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnPrestIns))
                        .addGap(25, 25, 25)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cmbPrestSucPres, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8))
                        .addGap(27, 27, 27))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(btnPrestMod)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(txtPrestCant, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtPrestVer)
                .addGap(74, 74, 74))
        );

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Sucursal"));

        jLabel1.setText("Código");

        jLabel2.setText("Teléfono");

        jLabel5.setText("Dirección");

        txtSucCod.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtSucCodFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtSucCodFocusLost(evt);
            }
        });
        txtSucCod.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSucCodActionPerformed(evt);
            }
        });

        btnSucIns.setText("Insertar");
        btnSucIns.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSucInsMouseClicked(evt);
            }
        });

        btnSucBorrar.setText("Borrar");
        btnSucBorrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSucBorrarMouseClicked(evt);
            }
        });

        btnSucMod.setText("Modificar");
        btnSucMod.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSucModMouseClicked(evt);
            }
        });

        btnSucVer.setText("Visualizar");
        btnSucVer.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSucVerMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtSucTlf, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 61, Short.MAX_VALUE)
                        .addComponent(txtSucDir, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtSucCod, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 42, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnSucMod, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnSucBorrar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnSucIns, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnSucVer))
                .addGap(18, 18, 18))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSucIns)
                    .addComponent(jLabel1)
                    .addComponent(txtSucCod, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(btnSucBorrar))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtSucDir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))))
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtSucTlf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSucMod))
                .addGap(18, 18, 18)
                .addComponent(btnSucVer)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        txtSucArea.setColumns(20);
        txtSucArea.setRows(5);
        jScrollPane2.setViewportView(txtSucArea);

        txtPrestArea.setColumns(20);
        txtPrestArea.setRows(5);
        jScrollPane1.setViewportView(txtPrestArea);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 239, Short.MAX_VALUE)
                    .addComponent(jScrollPane1))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtSucCodActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSucCodActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSucCodActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        controladorPantallaSucursal.cargarCb();  
        comboCarg=true;// TODO add your handling code here:
    }//GEN-LAST:event_formWindowOpened

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        
         comboCarg=false;// TODO add your handling code here:
    }//GEN-LAST:event_formWindowClosed

    private void txtSucCodFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtSucCodFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSucCodFocusGained

    private void txtSucCodFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtSucCodFocusLost
        // TODO add your handling code here:
          if (!txtSucCod.getText().isBlank()) {
        controladorPantallaSucursal.cargarDatosSuc(txtSucCod.getText(), txtSucDir, txtSucTlf);
          }
    }//GEN-LAST:event_txtSucCodFocusLost

    private void cmbPrestSucRPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_cmbPrestSucRPropertyChange
        // TODO add your handling code here:
       
    }//GEN-LAST:event_cmbPrestSucRPropertyChange

    private void cmbPrestSucPresPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_cmbPrestSucPresPropertyChange
        // TODO add your handling code here:
        
    }//GEN-LAST:event_cmbPrestSucPresPropertyChange

    private void btnSucInsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSucInsMouseClicked
        // TODO add your handling code here:
        boolean correcto=validarSucursal();
        if(correcto==true){
        controladorPantallaSucursal.insertarSuc(txtSucCod.getText(), txtSucDir.getText(), Integer.valueOf(txtSucTlf.getText()));
        }
    }//GEN-LAST:event_btnSucInsMouseClicked

    private void btnSucBorrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSucBorrarMouseClicked
        // TODO add your handling code here:
        boolean correcto=validarSucursal();
        if(correcto==true){
        controladorPantallaSucursal.borrarSuc(txtSucCod.getText());
        }
    }//GEN-LAST:event_btnSucBorrarMouseClicked

    private void btnSucModMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSucModMouseClicked
        // TODO add your handling code here:
        boolean correcto=validarSucursal();
        if(correcto==true){
        controladorPantallaSucursal.modificarSuc(txtSucCod.getText(), txtSucDir.getText(), Integer.valueOf(txtSucTlf.getText()));
        }
    }//GEN-LAST:event_btnSucModMouseClicked

    private void btnSucVerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSucVerMouseClicked
        // TODO add your handling code here:
        controladorPantallaSucursal.VisualizarSuc(txtSucArea);
    }//GEN-LAST:event_btnSucVerMouseClicked

    private void btnPrestInsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPrestInsMouseClicked
        // TODO add your handling code here:
      boolean correcto=validarPrestar();
        if(correcto==true){
        Sucursal s = (Sucursal) cmbPrestSucR.getSelectedItem();
        Sucursal sPres = (Sucursal) cmbPrestSucPres.getSelectedItem();
        PrestarPK ppk = new PrestarPK(s.getCodSucursal(), sPres.getCodSucursal());
        controladorPantallaSucursal.insertarPrest(ppk, Integer.valueOf(txtPrestCant.getText()));
        }
    }//GEN-LAST:event_btnPrestInsMouseClicked

    private void btnPrestModMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPrestModMouseClicked
        // TODO add your handling code here:
         boolean correcto=validarPrestar();
        if(correcto==true){
        Sucursal s = (Sucursal) cmbPrestSucR.getSelectedItem();
        Sucursal sPres = (Sucursal) cmbPrestSucPres.getSelectedItem();
        PrestarPK ppk = new PrestarPK(s.getCodSucursal(), sPres.getCodSucursal());
        controladorPantallaSucursal.modificarPrest(ppk, Integer.valueOf(txtPrestCant.getText()));
        }
    }//GEN-LAST:event_btnPrestModMouseClicked

    private void txtPrestVerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtPrestVerMouseClicked
        // TODO add your handling code here:
        controladorPantallaSucursal.VisualizarPres(txtPrestArea);
    }//GEN-LAST:event_txtPrestVerMouseClicked

    private void cmbPrestSucRItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmbPrestSucRItemStateChanged
        // TODO add your handling code here:
       if(comboCarg==true){
            Sucursal s = (Sucursal) cmbPrestSucR.getSelectedItem();
            Sucursal sPres = (Sucursal) cmbPrestSucPres.getSelectedItem();
            PrestarPK ppk = new PrestarPK(s.getCodSucursal(), sPres.getCodSucursal());
            controladorPantallaSucursal.cargarDatosPres(ppk, txtPrestCant);
       }
    }//GEN-LAST:event_cmbPrestSucRItemStateChanged

    private void cmbPrestSucPresItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmbPrestSucPresItemStateChanged
        // TODO add your handling code here:
        if(comboCarg==true){
            Sucursal s = (Sucursal) cmbPrestSucR.getSelectedItem();
            Sucursal sPres = (Sucursal) cmbPrestSucPres.getSelectedItem();
            PrestarPK ppk = new PrestarPK(s.getCodSucursal(), sPres.getCodSucursal());
            controladorPantallaSucursal.cargarDatosPres(ppk, txtPrestCant);
        }
    }//GEN-LAST:event_cmbPrestSucPresItemStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PantallaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PantallaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PantallaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PantallaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PantallaPrincipal().setVisible(true);
            }
        });
        
    }
    
    public JComboBox<Sucursal> getCmbPrestSucPres() {
        return cmbPrestSucPres;
    }
    
    public JComboBox<Sucursal> getCmbPrestSucR() {
        return cmbPrestSucR;
    }
    
    private boolean validarSucursal() {
        if (txtSucCod.getText().isBlank() == true) {
            JOptionPane.showMessageDialog(null, "Tiene que introducir el código");
            txtSucCod.requestFocus();
            return false;
        } else {
            Pattern p = Pattern.compile("^s\\d{2}$");
            boolean correcto = p.matcher(txtSucCod.getText()).matches();
            if (correcto == false) {
                JOptionPane.showMessageDialog(null, "Formato de código incorrecto(Formato válido:s+dos dígitos)");
                txtSucCod.requestFocus();
                txtSucCod.setText(" ");
                return false;
            }
        }
        
        if (txtSucTlf.getText().isBlank() == true) {
            JOptionPane.showMessageDialog(null, "Tiene que introducir el teléfono");
            txtSucTlf.requestFocus();
            return false;
        } else {
            Pattern p = Pattern.compile("^\\d{9}");
            boolean correcto = p.matcher(txtSucTlf.getText()).matches();
            if (correcto == false) {
                JOptionPane.showMessageDialog(null, "Formato de número de teléfono incorrecto");
                txtSucTlf.requestFocus();
                txtSucTlf.setText(" ");
                return false;
            }
        }
        return true;
    }

    private boolean validarPrestar() {
        if (cmbPrestSucPres.getSelectedItem().toString().equals(cmbPrestSucR.getSelectedItem().toString())) {
            JOptionPane.showMessageDialog(null, "La sucursal que realiza el préstamo no puede ser la que lo recibe");
            return false;
        }
        try {
            float cant = Float.valueOf(txtPrestCant.getText());
        } catch (NumberFormatException nfe) {
            JOptionPane.showMessageDialog(null, "Formato de cantidad incorrecto");
            txtPrestCant.requestFocus();
            return false;
        }
        return true;
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnPrestIns;
    private javax.swing.JButton btnPrestMod;
    private javax.swing.JButton btnSucBorrar;
    private javax.swing.JButton btnSucIns;
    private javax.swing.JButton btnSucMod;
    private javax.swing.JButton btnSucVer;
    private javax.swing.JComboBox<Sucursal> cmbPrestSucPres;
    private javax.swing.JComboBox<Sucursal> cmbPrestSucR;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea txtPrestArea;
    private javax.swing.JTextField txtPrestCant;
    private javax.swing.JButton txtPrestVer;
    private javax.swing.JTextArea txtSucArea;
    private javax.swing.JTextField txtSucCod;
    private javax.swing.JTextField txtSucDir;
    private javax.swing.JTextField txtSucTlf;
    // End of variables declaration//GEN-END:variables
}
